### ISSUE TITLE
[Question] Nested tabs

### ISSUE THREAD

**Issue by pedr0-fr** [Kaifuny/vuepress-plugin-tabs#22]
I need nested tabs for a set of programming languages in different environments. I need two levels of tabs like shown below. Any idea how to do it?

![Screenshot from 2020-10-07 04-15-05](https://user-images.githubusercontent.com/16596928/95285280-54560580-0858-11eb-985a-d15da6a11b00.png)

**Comment by pedr0-fr** [comment]
I was able to do it with the help of someone else... It's quite easy to make a syntax and think that it's not possible


```
::::::: tabs
:::::: tab tab1
::::: tabs
:::: tab Python
`print('Hello world')`
:::
::::
:::: tab Javascript
`console.log("Hello world");`
::::
:::::
::::::
:::::: tab tab2
Other tabs and contents will goes here
::::::
:::::::
```

**Comment by nandi95** [comment]
@superbiger can the above be added to the documentation?
